theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: false
  breadcrumb:
    position: after-hero
  logo:
    footer: '/assets/images/icon-white.svg'
  posts:
    index:
      layout: grid